spring.application.name=sgajwt
spring.datasource.url=jdbc:postgresql://localhost:5432/angular_db
spring.datasource.username=pgAdmin
spring.datasource.password=Devel0pment!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update

jwt.secret=77212492f47cedd4e74f9da12a38d1d37bdf1ee4f73e2f3a0ff02cc0bdf90e1e
jwt.expiration=3600

# swagger-ui custom path
springdoc.swagger-ui.path=/api/v1/auth/swagger-ui.html
springdoc.api-docs.path=/api/v1/auth/api-docs